name: build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    name: Build & Unit-Testing
    strategy:
      matrix:
        module: [Example]
        swift: [5.5]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Swift
      uses: slashmo/install-swift@v0.1.0
      with:
        version: ${{ matrix.swift }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  lint:
    name: Linting
    needs: test

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Lint (check)
      uses: norio-nomura/action-swiftlint@3.2.1
    - name: Lint (fix)
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --fix
    - name: Check for changes
      run: |
        echo "GIT_DIFF_STAT=$(git diff --stat)" >> $GITHUB_ENV
    - name: Get issue number
      if: ${{ env.GIT_DIFF_STAT != '' }}
      run: |
        echo "GITHUB_ISSUE_NUMBER=$(git log -n 1 --oneline | sed -E 's/^[^#]*$//')" >> $GITHUB_ENV
    - name: Commit and push fixes
      if: ${{ env.GIT_DIFF_STAT != '' }}
      run: |
        git config --global user.name swift-all-stars
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git commit -a -m "swiftlint fixes. #${GITHUB_ISSUE_NUMBER}"
        git push
