name: build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    name: Testing

    strategy:
      matrix:
        module: [Example]
        swift: [5.5]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Swift
      uses: slashmo/install-swift@v0.1.0
      with:
        version: ${{ matrix.swift }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Lint
      uses: norio-nomura/action-swiftlint@3.2.1
      env:
        WORKING_DIRECTORY: Sources
    - name: Generate docs
      uses: sersoft-gmbh/swifty-docs-action@v1
      with:
        output: docs
